"""Tests for pyp6.config."""

import os

import pytest

from pyp6.config import (
    add_recent_preset,
    ensure_app_dirs,
    format_duration,
    format_size,
    load_config,
    load_drawn_library,
    load_recent_presets,
    read_preset_manifest,
    safe_base_name,
    save_config_value,
    save_drawn_library,
    write_preset_manifest,
)


def test_ensure_app_dirs_creates_temp(tmp_path, monkeypatch):
    """ensure_app_dirs should create the temp directory if missing."""
    fake_temp = str(tmp_path / "pyp6_temp")
    monkeypatch.setattr("pyp6.config.TEMP_DIR", fake_temp)
    monkeypatch.setattr("pyp6.constants.TEMP_DIR", fake_temp)
    ensure_app_dirs()
    assert os.path.isdir(fake_temp)


# ---------------------------------------------------------------------------
# safe_base_name
# ---------------------------------------------------------------------------


def test_safe_base_name_plain():
    assert safe_base_name("/path/to/my_file.wav") == "my_file"


def test_safe_base_name_no_extension():
    assert safe_base_name("/path/to/my_file") == "my_file"


def test_safe_base_name_unicode_accent():
    # é decomposes to e + combining acute via NFKD; the combining mark is
    # then dropped by the ASCII encode step.
    assert safe_base_name("café.wav") == "cafe"


def test_safe_base_name_transliterate_german():
    assert safe_base_name("Straße.wav") == "Strasse"


def test_safe_base_name_transliterate_nordic():
    # ø transliterates to "oe" per _TRANSLITERATE, so "møøse" → "moeoese"
    assert safe_base_name("møøse.wav") == "moeoese"


def test_safe_base_name_reserved_windows_name():
    # FAT/Windows device names must not be used as filenames.
    assert safe_base_name("CON.wav") == "CON_"
    assert safe_base_name("NUL.wav") == "NUL_"
    assert safe_base_name("COM1.wav") == "COM1_"
    assert safe_base_name("LPT9.wav") == "LPT9_"


def test_safe_base_name_reserved_is_case_insensitive():
    # The check is against the uppercased form.
    assert safe_base_name("con.wav") == "con_"


def test_safe_base_name_max_len():
    long_name = "a" * 100 + ".wav"
    result = safe_base_name(long_name)
    assert len(result) <= 48


def test_safe_base_name_custom_max_len():
    result = safe_base_name("abcdefghij.wav", max_len=5)
    assert len(result) <= 5


def test_safe_base_name_fat_forbidden_chars():
    # Characters FAT rejects should be replaced with underscores.
    result = safe_base_name('file<>:"/\\|?*.wav')
    for ch in '<>:"/\\|?*':
        assert ch not in result


def test_safe_base_name_leading_dot_dropped():
    # Hidden files on Unix (.hidden) must not reach the FAT drive.
    result = safe_base_name(".hidden.wav")
    assert not result.startswith(".")


def test_safe_base_name_empty_returns_fallback():
    assert safe_base_name("") == "sample"
    assert safe_base_name(None) == "sample"


def test_safe_base_name_custom_fallback():
    assert safe_base_name("", fallback="untitled") == "untitled"


def test_safe_base_name_strip_tags_trim():
    # _trim_<bank><pad>_<hex> is the pattern generated by derived_temp_path.
    result = safe_base_name("kick_trim_A1_deadbeef.wav", strip_tags=True)
    assert result == "kick"


def test_safe_base_name_strip_tags_chop():
    result = safe_base_name("loop_chop_cafe1234.wav", strip_tags=True)
    assert result == "loop"


def test_safe_base_name_strip_tags_idempotent():
    # A name with no temp tag should not change.
    result = safe_base_name("snare.wav", strip_tags=True)
    assert result == "snare"


def test_safe_base_name_no_strip_tags_by_default():
    # Without strip_tags the suffix is kept.
    result = safe_base_name("kick_trim_deadbeef.wav")
    assert "trim" in result


# ---------------------------------------------------------------------------
# format_duration
# ---------------------------------------------------------------------------


def test_format_duration_none():
    assert format_duration(None) == "--:--"


def test_format_duration_zero():
    assert format_duration(0) == "0:00.0"


def test_format_duration_one_minute():
    assert format_duration(60) == "1:00.0"


def test_format_duration_fractional_seconds():
    assert format_duration(90.5) == "1:30.5"


def test_format_duration_sub_minute():
    assert format_duration(5.9) == "0:05.9"


# ---------------------------------------------------------------------------
# format_size
# ---------------------------------------------------------------------------


def test_format_size_none():
    assert format_size(None) == "--"


def test_format_size_megabytes():
    result = format_size(2 * 1024 * 1024)
    assert "MB" in result
    assert "2.00" in result


def test_format_size_kilobytes():
    # Anything below 0.1 MB is shown in KB.
    result = format_size(512)
    assert "KB" in result


def test_format_size_zero():
    result = format_size(0)
    assert "KB" in result or "MB" in result  # either is acceptable; no crash


# ---------------------------------------------------------------------------
# Config I/O round-trips
# ---------------------------------------------------------------------------


@pytest.fixture
def isolated_config(tmp_path, monkeypatch):
    """Redirect config I/O to a fresh tmp directory."""
    cfg = str(tmp_path / "config.json")
    monkeypatch.setattr("pyp6.config.CONFIG_FILE", cfg)
    monkeypatch.setattr("pyp6.config.APP_DIR", str(tmp_path))
    return tmp_path


def test_load_config_missing_file(isolated_config):
    assert load_config() == {}


def test_save_and_load_config_string(isolated_config):
    save_config_value("theme", "dracula")
    assert load_config()["theme"] == "dracula"


def test_save_and_load_config_int(isolated_config):
    save_config_value("default_slices", 16)
    assert load_config()["default_slices"] == 16


def test_save_config_preserves_existing_keys(isolated_config):
    save_config_value("key_a", "a")
    save_config_value("key_b", "b")
    data = load_config()
    assert data["key_a"] == "a"
    assert data["key_b"] == "b"


def test_save_config_overwrites_same_key(isolated_config):
    save_config_value("theme", "dark")
    save_config_value("theme", "latte")
    assert load_config()["theme"] == "latte"


# ---------------------------------------------------------------------------
# add_recent_preset
# ---------------------------------------------------------------------------


def test_add_recent_preset_first_entry(isolated_config):
    add_recent_preset("/presets/my_kit")
    assert load_recent_presets() == ["/presets/my_kit"]


def test_add_recent_preset_most_recent_first(isolated_config):
    add_recent_preset("/presets/a")
    add_recent_preset("/presets/b")
    recents = load_recent_presets()
    assert recents[0] == "/presets/b"
    assert recents[1] == "/presets/a"


def test_add_recent_preset_deduplication(isolated_config):
    add_recent_preset("/presets/a")
    add_recent_preset("/presets/b")
    add_recent_preset("/presets/a")  # re-add: should move to front, not duplicate
    recents = load_recent_presets()
    assert recents == ["/presets/a", "/presets/b"]


def test_add_recent_preset_capped_at_five(isolated_config):
    for i in range(7):
        add_recent_preset(f"/presets/{i}")
    recents = load_recent_presets()
    assert len(recents) == 5
    assert recents[0] == "/presets/6"  # most recent


# ---------------------------------------------------------------------------
# Preset manifest round-trip
# ---------------------------------------------------------------------------


def test_write_and_read_preset_manifest(tmp_path):
    data = {
        "format_version": 3,
        "banks": {"A": {"pads": {"1": {"filepath": "BANK_A/PAD_1/kick.wav"}}}},
    }
    write_preset_manifest(str(tmp_path), data)
    result = read_preset_manifest(str(tmp_path))
    assert result == data


def test_read_preset_manifest_missing(tmp_path):
    assert read_preset_manifest(str(tmp_path)) is None


def test_read_preset_manifest_malformed(tmp_path):
    (tmp_path / "preset.json").write_text("not valid json {{{")
    assert read_preset_manifest(str(tmp_path)) is None


def test_read_preset_manifest_no_banks_key(tmp_path):
    (tmp_path / "preset.json").write_text('{"format_version": 3}')
    assert read_preset_manifest(str(tmp_path)) is None


# ---------------------------------------------------------------------------
# Drawn waveform library round-trip
# ---------------------------------------------------------------------------


@pytest.fixture
def isolated_lib(tmp_path, monkeypatch):
    lib_file = str(tmp_path / "waveforms.json")
    monkeypatch.setattr("pyp6.config.WAVEFORM_LIB_FILE", lib_file)
    monkeypatch.setattr("pyp6.config.APP_DIR", str(tmp_path))
    return tmp_path


def test_load_drawn_library_empty(isolated_lib):
    assert load_drawn_library() == {}


def test_save_and_load_drawn_library(isolated_lib):
    library = {
        "MyWave": {
            "kind": "draw",
            "name": "MyWave",
            "a": [0.0, 1.0, 0.0, -1.0, 0.0],
            "b": [0.0, 0.5, 0.0, -0.5, 0.0],
        }
    }
    assert save_drawn_library(library) is True
    loaded = load_drawn_library()
    assert "MyWave" in loaded
    assert loaded["MyWave"]["a"] == [0.0, 1.0, 0.0, -1.0, 0.0]


def test_save_drawn_library_filters_entries_without_shape(isolated_lib):
    """An entry with no 'a' data must not make it into the saved file."""
    library = {
        "Good": {"kind": "draw", "name": "Good", "a": [0.0, 1.0, 0.0], "b": []},
        "Bad": {"kind": "draw", "name": "Bad"},  # no 'a' key
    }
    save_drawn_library(library)
    loaded = load_drawn_library()
    assert "Good" in loaded
    # 'Bad' has no 'a' list — load_drawn_library skips it
    assert "Bad" not in loaded


def test_load_drawn_library_ignores_malformed_file(isolated_lib, monkeypatch):
    lib_path = str(isolated_lib / "waveforms.json")
    with open(lib_path, "w") as f:
        f.write("not json")
    assert load_drawn_library() == {}
